global:
  scrape_interval: 15s # 15초마다 데이터 수집

scrape_configs:
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8081'] # Docker 내부 서비스 이름과 포트

  - job_name: 'settlement-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['settlement-service:8082']